BUZZWORDS = [
    # Overused action verbs
    "leverage", "synergize", "operationalize", "ideate", "strategize",
    "revolutionize", "disrupt", "empower", "unlock", "supercharge",
    "accelerate", "streamline", "optimize", "scale", "pivot",
    "circle back", "double down", "move the needle", "take it offline",
    "boil the ocean", "peel back the onion", "drink the kool-aid",

    # Hollow nouns
    "synergy", "ecosystem", "bandwidth", "deep dive", "paradigm shift",
    "game changer", "thought leader", "visionary", "ninja", "rockstar",
    "guru", "evangelist", "disruptor", "innovator", "trailblazer",
    "changemaker", "storyteller", "value proposition", "low-hanging fruit",

    # Corporate filler
    "at the end of the day", "it is what it is", "think outside the box",
    "best practices", "win-win", "core competency", "value add",
    "going forward", "touch base", "take ownership", "accountability",
    "transparency", "hustle", "grind", "passion",

    # Humble-brag openers
    "excited to announce", "humbled", "blessed", "grateful",
    "thrilled", "honored", "proud to share", "i never thought",
    "pinch me", "surreal moment", "still processing",
    "words cannot express", "overwhelmed with gratitude",

    # Fake vulnerability / storytelling hooks
    "here's what it taught me",
    "here's what no one tells you",
    "here's the thing",
    "let that sink in",
    "i'll be honest",
    "real talk",
    "story time",
    "unpopular opinion",
    "hot take",
    "this changed everything",
    "this is not a flex",
    "i was wrong",
    "i failed",
    "i almost quit",
    "nobody talks about this",
    "no one talks about this",
    "we need to talk about",
    "can we normalize",
    "raise your hand if",
    "posting this because",
    "i debated posting this",
    "i never post but",

    # Listicle / engagement bait
    "do this every day",
    "follow for more",
    "comment below",
    "drop a",
    "repost if you agree",
    "save this post",
    "share this with someone",
    "tag someone who",
    "the algorithm",
    "engage with this post",
    "like and comment",
    "top tips",
    "x things i learned",
    "x lessons from",
    "x mistakes",
    "x ways to",
    "thread incoming",
    "a thread",

    # Narrative dramatization
    "life is too short",
    "stop waiting",
    "just start",
    "take the leap",
    "trust the process",
    "embrace the journey",
    "journey",
    "the grind is real",
    "consistency is key",
    "success is a mindset",
    "your network is your net worth",
    "work smarter not harder",
    "done is better than perfect",
    "fail forward",
    "growth mindset",
    "level up",
    "next level",
    "game plan",
    "crushing it",
    "killing it",
    "nailing it",

    # LinkedIn-specific identity words
    "thought leader", "authentic", "personal brand",
    "building in public", "my why", "find your why",
    "passion project", "side hustle", "entrepreneur",
    "solopreneur", "founder mode", "startup life",
]
